export const CALIBRATION_DURATION_MS = 2_000;
export const PROMPT_DURATION_SECONDS = 5;
export const PROMPT_COUNT = 3;
export const GUIDED_SESSION_DURATION_MS =
  PROMPT_DURATION_SECONDS * PROMPT_COUNT * 1_000;
export const CAPTURE_DURATION_MS =
  CALIBRATION_DURATION_MS + GUIDED_SESSION_DURATION_MS;
export const FORMATION_DURATION_MS = 3_000;
export const TOTAL_EXPERIENCE_DURATION_MS =
  CAPTURE_DURATION_MS + FORMATION_DURATION_MS;
